#!/usr/bin/env node
'use strict';
// ── setup.js ──────────────────────────────────────────────────────────────────
// Run ONCE on first install:  node setup.js
// Guides you through API key entry interactively and writes .env.
// After this, just use START_BOT.bat or START_BOT.sh every time.
// ─────────────────────────────────────────────────────────────────────────────

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');
const { execSync } = require('child_process');

const ROOT = __dirname;
const ENV_FILE = path.join(ROOT, '.env');

const C = {
  green: '\x1b[32m', yellow: '\x1b[33m', cyan: '\x1b[36m',
  bold: '\x1b[1m', reset: '\x1b[0m', grey: '\x1b[90m',
};

const ok   = s => console.log(`${C.green}✅ ${s}${C.reset}`);
const warn = s => console.log(`${C.yellow}⚠️  ${s}${C.reset}`);
const info = s => console.log(`${C.cyan}ℹ️  ${s}${C.reset}`);

console.clear();
console.log(`${C.bold}${C.cyan}
╔══════════════════════════════════════════════════════════╗
║       🤖  ALADDIN BOT — FIRST-TIME SETUP                 ║
╚══════════════════════════════════════════════════════════╝
${C.reset}`);

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def = '') => new Promise(res => {
  const hint = def ? ` ${C.grey}[${def}]${C.reset}` : '';
  rl.question(`  ${q}${hint}: `, ans => res(ans.trim() || def));
});
const askSecret = (q) => new Promise(res => {
  process.stdout.write(`  ${q}: `);
  process.stdin.setRawMode?.(true);
  let input = '';
  process.stdin.on('data', function handler(ch) {
    ch = ch.toString();
    if (ch === '\n' || ch === '\r') {
      process.stdin.setRawMode?.(false);
      process.stdin.removeListener('data', handler);
      process.stdout.write('\n');
      res(input);
    } else if (ch === '\u0003') {
      process.exit();
    } else if (ch === '\u007f') {
      if (input.length > 0) { input = input.slice(0, -1); process.stdout.write('\b \b'); }
    } else {
      input += ch;
      process.stdout.write('*');
    }
  });
  process.stdin.resume();
});

async function run() {
  // Step 1: Install deps
  console.log('\n── Step 1: Installing dependencies ──────────────────────────');
  if (!fs.existsSync(path.join(ROOT, 'node_modules', 'express'))) {
    info('Running npm install...');
    execSync('npm install --ignore-scripts', { cwd: ROOT, stdio: 'inherit' });
    ok('Dependencies installed');
  } else {
    ok('Dependencies already installed');
  }

  // Step 2: API keys
  console.log('\n── Step 2: API Keys ─────────────────────────────────────────');
  info('Get your OANDA keys at: https://www.oanda.com/demo-account/');
  info('(Use the Practice environment first — it\'s free and risk-free)\n');

  const oandaKey    = await ask('OANDA API Key (leave blank to skip for now)', '');
  const oandaAcct   = await ask('OANDA Account ID (e.g. 001-001-1234567-001)', '');
  const oandaEnv    = await ask('OANDA environment', 'practice');
  const paperMode   = await ask('Paper mode? (true = safe, false = live)', 'true');

  console.log('\n── Step 3: Telegram Alerts (optional) ───────────────────────');
  info('Create a bot at: https://t.me/BotFather → /newbot');
  info('Get your chat ID: https://t.me/userinfobot\n');
  const tgToken     = await ask('Telegram Bot Token (leave blank to skip)', '');
  const tgChat      = await ask('Telegram Chat ID', '');

  console.log('\n── Step 4: AI Decisions (optional) ──────────────────────────');
  info('Get Anthropic API key at: https://console.anthropic.com\n');
  const anthropicKey = await ask('Anthropic API Key (leave blank to skip)', '');

  console.log('\n── Step 5: External Data (optional) ─────────────────────────');
  info('Get free Alpha Vantage key at: https://www.alphavantage.co/support/#api-key\n');
  const avKey       = await ask('Alpha Vantage API Key (leave blank to skip)', '');

  // Generate security key
  const hmacKey = require('crypto').randomBytes(24).toString('hex');
  const backupKey = require('crypto').randomBytes(24).toString('hex');

  // Write .env
  const envContent = [
    '# ── Aladdin Bot Configuration ────────────────────────────',
    `# Generated by setup.js on ${new Date().toISOString()}`,
    '',
    '# ── OANDA ───────────────────────────────────────────────',
    `OANDA_API_KEY=${oandaKey}`,
    `OANDA_ACCOUNT_ID=${oandaAcct}`,
    `OANDA_ENV=${oandaEnv}`,
    '',
    '# ── Mode ────────────────────────────────────────────────',
    `PAPER_MODE=${paperMode}`,
    'BACKTEST_MODE=false',
    '',
    '# ── Telegram ─────────────────────────────────────────────',
    `TELEGRAM_BOT_TOKEN=${tgToken}`,
    `TELEGRAM_CHAT_ID=${tgChat}`,
    '',
    '# ── AI Decisions ─────────────────────────────────────────',
    `ANTHROPIC_API_KEY=${anthropicKey}`,
    '',
    '# ── External Data ────────────────────────────────────────',
    `ALPHA_VANTAGE_API_KEY=${avKey}`,
    '',
    '# ── Security (auto-generated) ────────────────────────────',
    `AUDIT_HMAC_KEY=${hmacKey}`,
    `BACKUP_KEY=${backupKey}`,
    '',
    '# ── Ports ────────────────────────────────────────────────',
    'HEALTH_PORT=8080',
    'DASHBOARD_PORT=3000',
    'METRICS_PORT=9090',
    '',
    '# ── Performance ──────────────────────────────────────────',
    'PRICE_REFRESH_MS=30000',
  ].join('\n') + '\n';

  fs.writeFileSync(ENV_FILE, envContent);
  ok('.env saved');

  // Create dirs
  ['trade_logs', 'backups', 'config'].forEach(d => fs.mkdirSync(path.join(ROOT, d), { recursive: true }));
  ok('Directories created');

  // Done
  console.log(`
${C.bold}${C.green}
╔══════════════════════════════════════════════════════════╗
║  ✅  SETUP COMPLETE                                       ║
╠══════════════════════════════════════════════════════════╣
║  To start the bot:                                       ║`);
  if (process.platform === 'win32') {
    console.log(`║    Double-click: START_BOT.bat                           ║`);
    console.log(`║    Or run:       node launch.js                          ║`);
  } else {
    console.log(`║    Double-click: START_BOT.sh                            ║`);
    console.log(`║    Or run:       bash START_BOT.sh                       ║`);
  }
  console.log(`╚══════════════════════════════════════════════════════════╝
${C.reset}`);

  rl.close();
}

run().catch(e => { console.error(e.message); process.exit(1); });
